export const Users = [
    {
      id:1,
      profilePicture: "photo/profile/1.jpg",
      username: "Virat Kohli",
    },
    {
      id:2,
      profilePicture: "photo/profile/2.jpg",
      username: "Allu Arjun",
    },
    {
      id:3,
      profilePicture: "photo/profile/3.jpg",
      username: "Narendra Modi",
    },
    {
      id:4,
      profilePicture: "photo/profile/4.webp",
      username: "Cristiano Ronaldo",
    },
    {
      id:5,
      profilePicture: "photo/profile/5.png",
      username: "Friends",
    },
    {
      id:6,
      profilePicture: "photo/profile/6.jpg",
      username: "Adani",
    },
    {
      id:7,
      profilePicture: "photo/profile/7.jpg",
      username: "MS Dhoni",
    },
    {
      id:8,
      profilePicture: "photo/profile/8.jpg",
      username: "Justin Bieber",
    },
    {
      id:9,
      profilePicture: "photo/profile/9.webp",
      username: "Lionel Messi",
    },
    {
      id:10,
      profilePicture: "photo/profile/10.jpg",
      username: "Sundar Pichai",
    }, 
    {
      id:11,
      profilePicture: "photo/profile/11.jpg",
      username: "Akshay Kumar",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "photo/posts/1.webp",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "photo/posts/2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "photo/posts/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "photo/posts/4.webp",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "photo/posts/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "photo/posts/6.png",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "photo/posts/7.webp",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "photo/posts/8.webp",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "photo/posts/9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "photo/posts/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
     {
      id: 11,
      photo: "photo/posts/11.jpg",
      date: "1 week ago",
      userId: 11,
      like: 104,
      comment: 12,
    },
  ];